{{- range $name := list "engine" "worker" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jumi.fullname" $ }}-{{ $name }}
  labels:
    {{- include "jumi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ index $.Values $name "persistence" "size" }}
  {{- with index $.Values $name "persistence" "storageClass" }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jumi.fullname" . }}-postgres
  labels:
    {{- include "jumi.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
